name: WinUI Build Test

on:
#   push:
#     branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]
        platform: [x64]

    runs-on: windows-latest

    # TODO: Update environment variables.
    env:
      Solution_Name: GoodPass
      Project_Name: GoodPass
      # Test_Project_Name: App1.Tests.MSTest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
  
    - name: Restore
      run: dotnet restore $env:Solution_Name
  
    - name: Build
      run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:AppxPackageDir=C:\Package\x64
      env:
        BuildMode: SideloadOnly
        
    - name: Decode the pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.BASE64_ENCODED_PFX }}")
        $certificatePath = Join-Path -Path $env:ProjectDir -ChildPath GitHubActionsWorkflow.pfx
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
        
    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: MSIX Package
        path: GoodPass-v3/Packages/**/GoodPass*.msix
      
#   prlabeler:
#       permissions:
#         contents: read
#         pull-requests: write
#       runs-on: ubuntu-latest
#       steps:
#         - uses: actions/labeler@v4
#           with:
#             repo-token: "${{ secrets.AM_TOKEN }}"

    # - name: Test
    #   run: '& "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" ${env:Test_Project_Name}\bin\${{ matrix.platform }}\${{ matrix.configuration }}\**\${env:Test_Project_Name}.dll'
