name: WinUI Build Test

on:
#   push:
#     branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]
        platform: [x64]

    runs-on: windows-latest

    # TODO: Update environment variables.
    env:
      Solution_Name: GoodPass
      Project_Name: GoodPass
      # Test_Project_Name: App1.Tests.MSTest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
  
    - name: Restore
      run: dotnet restore $env:Solution_Name
  
    - name: Build
      run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}
      
#   prlabeler:
#       permissions:
#         contents: read
#         pull-requests: write
#       runs-on: ubuntu-latest
#       steps:
#         - uses: actions/labeler@v4
#           with:
#             repo-token: "${{ secrets.AM_TOKEN }}"

    # - name: Test
    #   run: '& "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" ${env:Test_Project_Name}\bin\${{ matrix.platform }}\${{ matrix.configuration }}\**\${env:Test_Project_Name}.dll'
